# Generated by Django 3.2 on 2021-07-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(default=1, upload_to='logos/'),
            preserve_default=False,
        ),
    ]
