# Generated by Django 3.2 on 2021-08-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0004_auto_20210813_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='pob',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
