# Generated by Django 3.2 on 2021-08-13 12:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0005_alter_university_pob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='fax_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
