# Generated by Django 3.2 on 2021-08-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0006_alter_university_fax_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='website',
            field=models.URLField(unique=True),
        ),
    ]
