# Generated by Django 3.2 on 2021-07-21 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('total_programs', models.IntegerField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.university')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('year_required', models.IntegerField()),
                ('degree_type', models.CharField(choices=[('BA', 'Bachelor of  Art'), ('BSc', 'Bachelor of Science'), ('BEd', 'Bachelor of Science'), ('MD', 'Master of Doctorate'), ('BPH', 'Bachelor of Pharmacy')], max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar_admin.faculty')),
            ],
        ),
    ]
