# Generated by Django 3.2 on 2021-08-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_admin', '0002_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='total_programs',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
