# Generated by Django 3.2 on 2021-08-20 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0008_alter_university_name'),
        ('registrar_admin', '0003_alter_faculty_total_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='super_admin.university'),
        ),
    ]
