# Generated by Django 3.2 on 2021-08-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0008_alter_university_name'),
        ('registrar_admin', '0008_alter_faculty_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('university', 'name')},
        ),
    ]
