# Generated by Django 3.2 on 2021-08-20 21:12

from django.db import migrations, models
import registrar_admin.validators


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_admin', '0009_alter_faculty_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='year_required',
            field=models.PositiveSmallIntegerField(validators=[registrar_admin.validators.validate_even]),
        ),
    ]
