# Generated by Django 3.2 on 2021-08-22 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_admin', '0010_alter_program_year_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['-id']},
        ),
    ]
