# Generated by Django 3.2 on 2021-06-26 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='student_id')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('registration_year', models.PositiveSmallIntegerField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='super_admin.university')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='graduates.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcadamicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', '1st semester'), ('2', '2nd semester')], max_length=20)),
                ('batch', models.IntegerField(default=1)),
                ('gpa', models.FloatField()),
                ('cgpa', models.FloatField()),
                ('acadamic_status', models.CharField(choices=[('promoted', 'promoted'), ('failed', 'failed'), ('suspended', 'suspended')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.student')),
            ],
        ),
    ]
