# Generated by Django 3.2 on 2021-07-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0003_auto_20210702_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acadamichistory',
            name='semester',
            field=models.CharField(choices=[('1st', '1 '), ('2nd', '2 ')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='acadamichistory',
            constraint=models.UniqueConstraint(fields=('batch', 'semester'), name='one_batch_semester'),
        ),
    ]
