# Generated by Django 3.2 on 2021-07-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0004_auto_20210702_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acadamichistory',
            name='semester',
            field=models.CharField(choices=[('1', '1st semester'), ('2', '2nd semester')], max_length=20),
        ),
    ]
