# Generated by Django 3.2 on 2021-07-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0005_alter_acadamichistory_semester'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='acadamichistory',
            name='one_batch_semester',
        ),
    ]
