# Generated by Django 3.2 on 2021-07-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0006_remove_acadamichistory_one_batch_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_id',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='student_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
