# Generated by Django 3.2 on 2021-07-05 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0007_auto_20210705_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acadamichistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.student', to_field='stud_id'),
        ),
    ]
