# Generated by Django 3.2 on 2021-07-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0008_alter_acadamichistory_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acadamichistory',
            name='batch',
            field=models.CharField(choices=[('Freshman', '1'), ('Sophomore', '2'), ('Junior', '3'), ('Senior', '4'), ('Graduate', '5')], max_length=20),
        ),
        migrations.AlterField(
            model_name='acadamichistory',
            name='semester',
            field=models.CharField(choices=[('1st semester', '1'), ('2nd semester', '2')], max_length=20),
        ),
    ]
