# Generated by Django 3.2 on 2021-07-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0009_auto_20210705_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acadamichistory',
            name='batch',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='acadamichistory',
            name='semester',
            field=models.CharField(choices=[('1', '1st semester'), ('2', '2nd semester')], max_length=20),
        ),
    ]
