# Generated by Django 3.2 on 2021-07-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0014_auto_20210715_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='student_image'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='qr_code',
            field=models.ImageField(default=1, upload_to='qr_codes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='ID Number '),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(max_length=200, verbose_name='middle name'),
        ),
    ]
