# Generated by Django 3.2 on 2021-07-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0015_auto_20210715_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='CGPA',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='GPA',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='dept',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
