# Generated by Django 3.2 on 2021-07-15 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0017_alter_certificate_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='graduates.student'),
        ),
    ]
