# Generated by Django 3.2 on 2021-07-15 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0018_alter_certificate_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='CGPA',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='GPA',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='dept',
            field=models.CharField(default=1, max_length=200, verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='school',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.student', verbose_name='student_id'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(upload_to='qr_codes')),
                ('image', models.ImageField(default='default.jpg', upload_to='student_image')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='graduates.student')),
            ],
        ),
    ]
