# Generated by Django 3.2 on 2021-07-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0019_auto_20210715_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='student_image'),
        ),
    ]
