# Generated by Django 3.2 on 2021-07-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0020_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registration_year',
        ),
    ]
