# Generated by Django 3.2 on 2021-08-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0024_certificate_uploaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='uploaded_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
