# Generated by Django 3.2 on 2021-08-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0025_alter_certificate_uploaded_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default=1, max_length=255, verbose_name='student name'),
            preserve_default=False,
        ),
    ]
