# Generated by Django 3.2 on 2021-08-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0027_auto_20210817_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='academichistory',
            name='level_of_completion',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
