# Generated by Django 3.2 on 2021-08-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0029_remove_academichistory_level_of_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level_of_completion',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
