# Generated by Django 3.2 on 2021-08-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0030_student_level_of_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level_of_completion',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
