# Generated by Django 3.2 on 2021-08-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0031_alter_student_level_of_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level_of_completion',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
