# Generated by Django 3.2 on 2021-08-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0032_alter_student_level_of_completion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academichistory',
            options={'ordering': ['-semester']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-registration_year']},
        ),
        migrations.AddField(
            model_name='academichistory',
            name='CGPA',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='GPA',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='academichistory',
            name='academic_status',
            field=models.CharField(choices=[('Promoted', 'Promoted'), ('Dismissed', 'Dismissed'), ('suspended', 'suspended')], max_length=20),
        ),
        migrations.AlterField(
            model_name='academichistory',
            name='batch',
            field=models.CharField(choices=[('1', '1st year'), ('2', '2nd year'), ('3', '3rd year'), ('4', '4th year'), ('5', '5th year'), ('6', '6th year')], max_length=20, verbose_name='Class Year'),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
