# Generated by Django 3.2 on 2021-08-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0033_auto_20210819_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academichistory',
            name='academic_status',
            field=models.CharField(blank=True, choices=[('Promoted', 'Promoted'), ('Dismissed', 'Dismissed'), ('suspended', 'suspended')], max_length=20, null=True),
        ),
    ]
