# Generated by Django 3.2 on 2021-08-20 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0034_alter_academichistory_academic_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academichistory',
            options={'ordering': ['-uploaded_date']},
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GPA', models.FloatField(default=0.0)),
                ('CGPA', models.FloatField(default=0.0)),
                ('graduation_date', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.student')),
            ],
        ),
    ]
