# Generated by Django 3.2 on 2021-08-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0036_alter_academichistory_uploaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academichistory',
            name='uploaded_date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
    ]
