# Generated by Django 3.2 on 2021-08-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0037_alter_academichistory_uploaded_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
